#!/bin/bash

TEXTDOMAINDIR=/usr/share/locale 
TEXTDOMAIN=mx-switchuser

yad --question --title=$"User Switching" \
 --text=$"This tool allows you to switch to a different user without closing down your current session.

To return to the original user, simply press Ctrl-Alt-F7. Go back again with Ctrl-Alt-F8.

Do you want to switch to another user?"

if [ $? -eq 0 ] ; then
dm-tool switch-to-greeter

else
 exit 0

fi
